#!/usr/bin/env python3.10

import re
import sys
from collections import Counter

# Takes output of `git log --pretty=fuller`
if __name__ == "__main__":
    git_output = sys.stdin.read().splitlines()
    timezones = []

    for line in git_output:
        if re.search("^CommitDate", line):
            timezones.append(line.split()[-1])

    tz_count = Counter(timezones)

    for tz, count in sorted(tz_count.items(), key=lambda item: int(item[0])):
        print(f"{tz} {count}")
